services:
  frontoffice.web:
    container_name: leaderboard.frontoffice.web
    image: leaderboard.frontoffice.web
    ports:
      - "5110:5110"
    build:
      context: ./BE
      dockerfile: FrontOffice/FrontOffice.Web/Dockerfile
    env_file:
      - .env
    environment:
      Kestrel__Endpoints__Localhost__Url: http://0.0.0.0:5110
      Grpc__Identity__Endpoint: http://identity:5010
      Grpc__Chronicle__Endpoint: http://chronicle:5020
      Grpc__PlayerSearch__Endpoint: http://playersearch:5030

  backoffice.identity:
    container_name: leaderboard.backoffice.identity
    hostname: identity
    image: leaderboard.backoffice.identity
    ports:
      - "5010:5010"
    build:
      context: ./BE
      dockerfile: BackOffice/BackOffice.Identity/Dockerfile
    env_file:
      - .env
    environment:
      Kestrel__Endpoints__Localhost__Url: http://0.0.0.0:5010
      ConnectionStrings__IdentityDb: "Host=postgresql;Port=5432;Database=identity;Username=identity;Password=identity-1K2p1zvz52zag1@;Pooling=true;Minimum Pool Size=5;Maximum Pool Size=20;Include Error Detail=true"
      Kafka__Producer__PlayerMessage__BootstrapServers: kafka1:9092,kafka2:9092,kafka3:9092
      Kafka__Configuration__Player__BootstrapServers: kafka1:9092,kafka2:9092,kafka3:9092
    depends_on:
      - kafka1
      - kafka2
      - kafka3

  backoffice.chronicle:
    container_name: leaderboard.backoffice.chronicle
    hostname: chronicle
    image: leaderboard.backoffice.chronicle
    ports:
      - "5020:5020"
    build:
      context: ./BE
      dockerfile: BackOffice/BackOffice.Chronicle/Dockerfile
    env_file:
      - .env
    environment:
      Kestrel__Endpoints__Localhost__Url: http://0.0.0.0:5020
      Kafka__Consumer__MatchStatusMessage__BootstrapServers: kafka1:9092,kafka2:9092,kafka3:9092
      Kafka__Consumer__PlayerMessage__BootstrapServers: kafka1:9092,kafka2:9092,kafka3:9092
      ConnectionStrings__ChronicleDb: "Host=postgresql;Port=5432;Database=chronicle;Username=chronicle;Password=chronicle-ha90Hxzw09fh2x!;Pooling=true;Minimum Pool Size=5;Maximum Pool Size=20;Include Error Detail=true"
    depends_on:
      - postgresql

  backoffice.playersearch:
    container_name: leaderboard.backoffice.playersearch
    hostname: playersearch
    image: leaderboard.backoffice.playersearch
    ports:
      - "5030:5030"
    build:
      context: ./BE
      dockerfile: BackOffice/BackOffice.PlayerSearch/Dockerfile
    env_file:
      - .env
    environment:
      Kestrel__Endpoints__Localhost__Url: http://0.0.0.0:5030
      AWS__ServiceURL: http://dynamodb:8000/
    depends_on:
      - dynamodb

  backoffice.matchmaker:
    container_name: leaderboard.backoffice.matchmaker
    hostname: matchmaker
    image: leaderboard.backoffice.matchmaker
    build:
      context: ./BE
      dockerfile: BackOffice/BackOffice.Matchmaker/Dockerfile
    env_file:
      - .env
    environment:
      Kafka__Producer__MatchStatusMessage__BootstrapServers: kafka1:9092,kafka2:9092,kafka3:9092
      Kafka__Configuration__MatchStatus__BootstrapServers: kafka1:9092,kafka2:9092,kafka3:9092
    depends_on:
      - kafka1
      - kafka2
      - kafka3

  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: leaderboard.dynamodb
    hostname: dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal

  kafka1:
    container_name: leaderboard.kafka1
    image: confluentinc/cp-kafka:8.1.1
    ports:
      - "9100:9100"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka1:9092,CONTROLLER://kafka1:9093,EXTERNAL://:9100'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka1:9092,EXTERNAL://localhost:9100'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      CLUSTER_ID: 'leaderboard-cluster-id'
      # offset replication factor
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      # minimal count of synchronized replicas on a write
      # example: if value=2 and only 1 broker is available, write will be available
      # example: if value=1 and leader shut down before synchronization, data will be lost
      KAFKA_MIN_INSYNC_REPLICAS: 2
    volumes:
      - kafka1_data:/var/lib/kafka/data

  kafka2:
    container_name: leaderboard.kafka2
    image: confluentinc/cp-kafka:8.1.1
    ports:
      - "9101:9101"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_BROKER_ID: 2
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka2:9092,CONTROLLER://kafka2:9093,EXTERNAL://:9101'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka2:9092,EXTERNAL://localhost:9101'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      CLUSTER_ID: 'leaderboard-cluster-id'
      # offset replication factor
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      # minimal count of synchronized replicas on a write
      # example: if value=2 and only 1 broker is available, write will be available
      # example: if value=1 and leader shut down before synchronization, data will be lost
      KAFKA_MIN_INSYNC_REPLICAS: 2
    volumes:
      - kafka2_data:/var/lib/kafka/data

  kafka3:
    container_name: leaderboard.kafka3
    image: confluentinc/cp-kafka:8.1.1
    ports:
      - "9102:9102"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_BROKER_ID: 3
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka3:9092,CONTROLLER://kafka3:9093,EXTERNAL://:9102'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka3:9092,EXTERNAL://localhost:9102'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      CLUSTER_ID: 'leaderboard-cluster-id'
      # offset replication factor
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      # minimal count of synchronized replicas on a write
      # example: if value=2 and only 1 broker is available, write will be available
      # example: if value=1 and leader shut down before synchronization, data will be lost
      KAFKA_MIN_INSYNC_REPLICAS: 2
    volumes:
      - kafka3_data:/var/lib/kafka/data
        
  conduktor:
    container_name: leaderboard.conduktor
    image: conduktor/conduktor-console
    ports:
      - "8080:8080"
    environment:
      CDK_DATABASE_HOSTS_0_HOST: postgresql
      CDK_DATABASE_HOSTS_0_PORT: 5432
      CDK_DATABASE_NAME: conduktor
      CDK_DATABASE_USERNAME: "conduktor"
      CDK_DATABASE_PASSWORD: "conduktor-5zx%2fksaf@9xxs"
      CDK_AUTH_LOCALUSERS_0_EMAIL: "admin@conduktor.io"
      CDK_AUTH_LOCALUSERS_0_PASSWORD: "Password1234!"
    depends_on:
      - postgresql
    volumes:
      - conduktor_data:/var/conduktor

  postgresql:
    container_name: leaderboard.postgresql
    image: postgres:18
    hostname: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres-Wkd@saf2kf!Gf2%"
      POSTGRES_HOST_AUTH_METHOD: password
    volumes:
      - pg_data:/var/lib/postgresql
      - .init/Postgres/01-init-users.sql:/docker-entrypoint-initdb.d/01-init-users.sql

  frontend:
    container_name: leaderboard.frontend
    image: leaderboard.frontend
    build: ./FE
    ports:
      - "5173:5173"
    depends_on:
      - frontoffice.web

volumes:
  kafka1_data: {}
  kafka2_data: {}
  kafka3_data: {}
  conduktor_data: {}
  pg_data: {}
  dynamodb_data: {}