// <auto-generated />
using System;
using BackOffice.Chronicle.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackOffice.Chronicle.Migrations.Migrations
{
    [DbContext(typeof(ChronicleDbContext))]
    [Migration("20260309173628_Update_UniqueMatchId")]
    partial class Update_UniqueMatchId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackOffice.Chronicle.Data.Models.MatchDto", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("match_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id");

                    b.HasIndex("FinishedAt");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.HasIndex("StartedAt");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("BackOffice.Chronicle.Data.Models.MatchPlayerDto", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<long>("MatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("match_id");

                    b.Property<bool>("IsWin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_win");

                    b.HasKey("PlayerId", "MatchId");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerId", "IsWin");

                    b.ToTable("match_players", (string)null);
                });

            modelBuilder.Entity("BackOffice.Chronicle.Data.Models.MatchPlayerDto", b =>
                {
                    b.HasOne("BackOffice.Chronicle.Data.Models.MatchDto", null)
                        .WithMany("Players")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackOffice.Chronicle.Data.Models.MatchDto", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
