CREATE USER conduktor WITH ENCRYPTED PASSWORD 'conduktor-5zx%2fksaf@9xxs';
CREATE DATABASE conduktor;
GRANT ALL PRIVILEGES ON DATABASE conduktor TO conduktor;

CREATE USER chronicle WITH ENCRYPTED PASSWORD 'chronicle-ha90Hxzw09fh2x!';
CREATE DATABASE chronicle;
GRANT ALL PRIVILEGES ON DATABASE chronicle TO chronicle;

CREATE USER ladder WITH ENCRYPTED PASSWORD 'ladder-%kaHdkMp1@5xm23';
CREATE DATABASE ladder;
GRANT ALL PRIVILEGES ON DATABASE ladder TO ladder;

CREATE USER identity WITH ENCRYPTED PASSWORD 'identity-1K2p1zvz52zag1@';
CREATE DATABASE identity;
GRANT ALL PRIVILEGES ON DATABASE identity TO identity;